baseURL: /
languageCode: en-us
title: Remediant Home
theme: "rmd-base"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
params:
  logo: https://res.cloudinary.com/remediant/image/upload/w_50,h_50/v1544975038/header-logo.png