---
baseURL: "/"
languageCode: en-us
title: Remediant Home
theme: rmd
metaDataFormat: "yaml"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
params:
  logo: https://res.cloudinary.com/remediant/image/upload/w_50,h_50/v1544975038/header-logo.png
taxonomies:
  author: authors
  tag: tags
  category: categories
menu:
  sidenav:
  - name: Markdown (GitHub)
    parent: getting-started
    weight: 13
    identifier: markdown
  - name: Overview
    parent: shortcodes
    weight: 8
    identifier: shortcodes-overview
  - name: Updating this Site
    weight: 11
    identifier: getting-started
  - name: Online Editor (Forestry)
    parent: getting-started
    weight: 5
    identifier: forestry
  - name: Introduction
    parent: forestry
    weight: 6
    identifier: forestry-intro
  - name: Introduction
    parent: getting-started
    weight: 7
    identifier: introduction
  - name: Markdown
    parent: getting-started
    weight: 12
    identifier: markdown-all
  - name: Blockquotes
    parent: markdown
    weight: 20
  - name: Code Highlighting
    parent: markdown
    weight: 22
  - name: Alerts
    parent: shortcodes
    weight: 16
  - name: Shortcodes
    parent: markdown
    weight: 23
    identifier: shortcodes
  - name: Social Content
    parent: shortcodes
    weight: 14
  - name: Flowcharts
    parent: shortcodes
    weight: 18
    identifier: flowcharts
  - name: Introduction
    parent: markdown
    weight: 9
  - name: Lists
    parent: markdown
    weight: 19
  - name: Tables
    parent: markdown
    weight: 21
  - name: Typography
    parent: markdown
    weight: 15
  - name: Images
    parent: markdown
    weight: 17
