version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.59.1
    steps:
      - checkout
      - run:
          name: "Pulling submodules"
          command: git submodule init && git submodule update --remote
      - run:
          name: "Build Website with Hugo"
          command: HUGO_ENV=production hugo -D -v
      - run:
          name: "Test The Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public